# 1 Libraries

```{r}
library(fistools)
library(camtraptor)
library(tidyverse)
```

# 2 Input

```{r get data from drive}
download_gdrive_if_missing(gfileID = "1iSpC4QpRtEioPQob3ULAqj2wSOT5S3w8",
                           destfile = "./Drongengoed/Input/drongengoed.zip", 
                           email = Sys.getenv("email"),
                           update_always = TRUE)
# Note to student: you do not have the necessary rights to *make changes* in the Drive where this file is kept -- but you should have enough rights to access the file
# But no worries, if you need the latest export: ask anyone that works on the project to make a new export (make take a while) and update it in this Drive.
# It is essential that the new export be named drongengoed.zip so that it replaces the old files, but keeps the same gfileID
```

```{r unzip and read data}
# Unzip data
unzip("./Drongengoed/Input/drongengoed.zip", 
      exdir = "./Drongengoed/Input/Files")

# Read data
drg <- camtraptor::read_camtrap_dp(file = "./Drongengoed/Input/Files")
```

```{r unlink files}
unlink("./Drongengoed/Input/Files",
       recursive = TRUE)
file.remove("./Drongengoed/Input/drongengoed.zip")
```

# 3 Get relevant deployments

```{r}
drg$data$deployments <-  drg$data$deployments %>%
  mutate(year = year(start),
         month = month(start))
```

## 3.1 Older years (FYI only)

```{r for 2023 field season, eval = FALSE}
# dep <- drg$data$deployments %>%
#   filter(year == 2023,
#          month %in% 9:12)
```

```{r for 2024 field season, eval = FALSE}
# dep <- drg$data$deployments %>%
#   filter(year == 2024,
#          month %in% 9:11)
```

## 3.2 Current year

```{r for 2025 field season}
dep <- drg$data$deployments %>%
  filter(year == 2025,
         month %in% 10:11)
depID <- c(dep$deploymentID)
```

## 3.3 Filter for deployments with actual calibration within timeframe

```{r get deps with calibration}
deps_with_cal <- drg$data$observations %>%
  filter(deploymentID %in% depID) %>%
  filter(cameraSetup == "calibration")
deps_with_cal <- unique(deps_with_cal$deploymentID)

depID <- depID[depID %in% deps_with_cal]
```

# 4 Get relevant sequences

## 4.1 Species filter

```{r}
species <- c("Capreolus capreolus", "Dama dama", "Vulpes vulpes")
```

## 4.2 Combine all filters

```{r}
obs <- drg$data$observations %>%
  filter(deploymentID %in% depID) %>%
  filter(scientificName %in% species)

seqID <- c(unique(obs$sequenceID)) # All seq to do
```

# 5 Remove already-done sequences

```{r}
seq_done <- read_csv("./Drongengoed/Input/tracking_seq_done.csv")
seq_done <- c(seq_done$sequenceID)
```

```{r}
seqID <- seqID[!seqID %in% seq_done]
```

# 6 Open sequences in Agouti

```{r}
for (i in 1:length(seqID)) {
  # Open URL
  browseURL(url = paste0("https://www.agouti.eu/project/e10e6b2b-78fc-44ad-9d66-c4d0b1dd889e/observations/edit-sequence/",
                         seqID[i]))
  # append seqID to done file to skip next time
  write.table(data.frame(sequenceID = seqID[i]),
              "./Drongengoed/Input/tracking_seq_done.csv",
              append = TRUE,
              row.names = FALSE,
              col.names = FALSE)
  # Naar de volgende reeks of niet?
  if (!askYesNo("Do you wanna go to the next sequence?")) {
    break
  }
}
```

